# Generated by Django 5.2 on 2026-02-08 00:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('tenant_id', models.UUIDField(db_index=True, help_text='The tenant this record belongs to.')),
                ('user_id', models.UUIDField(db_index=True, help_text='User to notify.')),
                ('notification_type', models.CharField(choices=[('account.welcome', 'Welcome'), ('account.email_verified', 'Email Verified'), ('account.password_changed', 'Password Changed'), ('account.password_reset', 'Password Reset'), ('account.login_new_device', 'New Device Login'), ('account.subscription_changed', 'Subscription Changed'), ('finance.transaction_created', 'Transaction Created'), ('finance.transaction_posted', 'Transaction Posted'), ('finance.large_transaction', 'Large Transaction'), ('finance.low_balance', 'Low Balance'), ('finance.transfer_completed', 'Transfer Completed'), ('finance.account_created', 'Account Created'), ('finance.account_closed', 'Account Closed'), ('finance.net_worth_milestone', 'Net Worth Milestone'), ('social.debt_created', 'Debt Created'), ('social.debt_reminder', 'Debt Reminder'), ('social.debt_settled', 'Debt Settled'), ('social.settlement_received', 'Settlement Received'), ('social.expense_added', 'Expense Added'), ('social.group_invitation', 'Group Invitation'), ('social.group_expense_split', 'Expense Split'), ('social.balance_updated', 'Balance Updated'), ('system.announcement', 'Announcement'), ('system.maintenance', 'Maintenance'), ('system.feature_update', 'Feature Update')], db_index=True, help_text='Type of notification.', max_length=50)),
                ('category', models.CharField(choices=[('account', 'Account'), ('finance', 'Finance'), ('social', 'Social'), ('system', 'System')], db_index=True, help_text='Category for grouping.', max_length=20)),
                ('title', models.CharField(help_text='Notification title.', max_length=255)),
                ('message', models.TextField(help_text='Notification message.')),
                ('data', models.JSONField(blank=True, default=dict, help_text='Additional data.')),
                ('action_url', models.CharField(blank=True, help_text='Optional action URL.', max_length=500)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('read', 'Read'), ('archived', 'Archived'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('websocket_sent', models.BooleanField(default=False)),
                ('websocket_sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', 'status', '-created_at'], name='idx_notif_user_status'), models.Index(fields=['user_id', 'category', '-created_at'], name='idx_notif_user_category'), models.Index(fields=['tenant_id', 'notification_type'], name='idx_notif_tenant_type')],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('tenant_id', models.UUIDField(db_index=True, help_text='The tenant this record belongs to.')),
                ('user_id', models.UUIDField(db_index=True, help_text='User these preferences belong to.')),
                ('category', models.CharField(choices=[('account', 'Account'), ('finance', 'Finance'), ('social', 'Social'), ('system', 'System')], help_text='Notification category.', max_length=20)),
                ('in_app_enabled', models.BooleanField(default=True, help_text='Show in-app notifications.')),
                ('email_enabled', models.BooleanField(default=True, help_text='Send email notifications.')),
                ('push_enabled', models.BooleanField(default=False, help_text='Send push notifications (future).')),
                ('email_frequency', models.CharField(choices=[('immediate', 'Immediate'), ('daily', 'Daily Digest'), ('weekly', 'Weekly Digest'), ('never', 'Never')], default='immediate', max_length=20)),
                ('disabled_types', models.JSONField(blank=True, default=list, help_text='List of disabled notification types.')),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
                'db_table': 'notification_preferences',
                'indexes': [models.Index(fields=['user_id', 'category'], name='idx_pref_user_category')],
                'unique_together': {('user_id', 'category')},
            },
        ),
    ]
