# Generated by Django 5.2 on 2026-02-07 21:15

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('archived', 'archived')], default='active', max_length=20)),
                ('share_status', models.CharField(choices=[('not_shared', 'not_shared'), ('pending', 'pending'), ('accepted', 'accepted'), ('declined', 'declined')], default='not_shared', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'social_contact',
            },
        ),
        migrations.CreateModel(
            name='ContactGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('members', models.ManyToManyField(blank=True, related_name='contact_groups', to='social.contact')),
            ],
            options={
                'db_table': 'social_contact_group',
            },
        ),
        migrations.CreateModel(
            name='ExpenseGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('default_currency', models.CharField(default='USD', max_length=3)),
                ('include_self', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member_contacts', models.ManyToManyField(blank=True, related_name='expense_groups', to='social.contact')),
            ],
            options={
                'db_table': 'social_expense_group',
            },
        ),
        migrations.CreateModel(
            name='GroupExpense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('description', models.CharField(max_length=500)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency_code', models.CharField(default='USD', max_length=3)),
                ('paid_by_owner', models.BooleanField(default=True)),
                ('split_method', models.CharField(choices=[('equal', 'equal'), ('exact', 'exact'), ('percentage', 'percentage'), ('shares', 'shares')], default='equal', max_length=20)),
                ('expense_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'active'), ('settled', 'settled'), ('cancelled', 'cancelled')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='social.expensegroup')),
                ('paid_by_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_expenses', to='social.contact')),
            ],
            options={
                'db_table': 'social_group_expense',
            },
        ),
        migrations.CreateModel(
            name='ExpenseSplit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_owner', models.BooleanField(default=False)),
                ('share_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('settled_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('settled', 'settled'), ('partial', 'partial')], default='pending', max_length=20)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_splits', to='social.contact')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='social.groupexpense')),
            ],
            options={
                'db_table': 'social_expense_split',
            },
        ),
        migrations.CreateModel(
            name='PeerDebt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('direction', models.CharField(choices=[('lent', 'lent'), ('borrowed', 'borrowed')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency_code', models.CharField(default='USD', max_length=3)),
                ('settled_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('description', models.TextField(blank=True, null=True)),
                ('debt_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('settled', 'settled'), ('cancelled', 'cancelled')], default='active', max_length=20)),
                ('linked_transaction_id', models.UUIDField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='social.contact')),
            ],
            options={
                'db_table': 'social_peer_debt',
            },
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('from_is_owner', models.BooleanField(default=False)),
                ('to_is_owner', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency_code', models.CharField(default='USD', max_length=3)),
                ('method', models.CharField(default='cash', max_length=50)),
                ('settlement_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements_from', to='social.contact')),
                ('linked_debts', models.ManyToManyField(blank=True, related_name='settlements', to='social.peerdebt')),
                ('linked_splits', models.ManyToManyField(blank=True, related_name='settlements', to='social.expensesplit')),
                ('to_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements_to', to='social.contact')),
            ],
            options={
                'db_table': 'social_settlement',
            },
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['tenant_id', 'status'], name='social_cont_tenant__277a9b_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['tenant_id', 'email'], name='social_cont_tenant__eb8f6b_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['linked_user'], name='social_cont_linked__b86e4a_idx'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', False)), fields=('tenant_id', 'email'), name='unique_contact_email_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='contactgroup',
            index=models.Index(fields=['tenant_id'], name='social_cont_tenant__1243f4_idx'),
        ),
        migrations.AddIndex(
            model_name='expensegroup',
            index=models.Index(fields=['tenant_id'], name='social_expe_tenant__016d99_idx'),
        ),
        migrations.AddIndex(
            model_name='groupexpense',
            index=models.Index(fields=['tenant_id', 'status'], name='social_grou_tenant__cd007d_idx'),
        ),
        migrations.AddIndex(
            model_name='groupexpense',
            index=models.Index(fields=['group'], name='social_grou_group_i_412044_idx'),
        ),
        migrations.AddIndex(
            model_name='groupexpense',
            index=models.Index(fields=['expense_date'], name='social_grou_expense_8bb3f9_idx'),
        ),
        migrations.AddIndex(
            model_name='expensesplit',
            index=models.Index(fields=['expense'], name='social_expe_expense_25f628_idx'),
        ),
        migrations.AddIndex(
            model_name='expensesplit',
            index=models.Index(fields=['contact'], name='social_expe_contact_c25d6d_idx'),
        ),
        migrations.AddConstraint(
            model_name='expensesplit',
            constraint=models.CheckConstraint(condition=models.Q(('contact__isnull', False), ('is_owner', True), _connector='OR'), name='split_must_have_contact_or_be_owner'),
        ),
        migrations.AddIndex(
            model_name='peerdebt',
            index=models.Index(fields=['tenant_id', 'status'], name='social_peer_tenant__ffc53f_idx'),
        ),
        migrations.AddIndex(
            model_name='peerdebt',
            index=models.Index(fields=['tenant_id', 'contact'], name='social_peer_tenant__dde514_idx'),
        ),
        migrations.AddIndex(
            model_name='peerdebt',
            index=models.Index(fields=['debt_date'], name='social_peer_debt_da_2e1cda_idx'),
        ),
        migrations.AddIndex(
            model_name='peerdebt',
            index=models.Index(fields=['due_date'], name='social_peer_due_dat_165d07_idx'),
        ),
        migrations.AddIndex(
            model_name='settlement',
            index=models.Index(fields=['tenant_id'], name='social_sett_tenant__7b8a24_idx'),
        ),
        migrations.AddIndex(
            model_name='settlement',
            index=models.Index(fields=['settlement_date'], name='social_sett_settlem_2365a0_idx'),
        ),
        migrations.AddIndex(
            model_name='settlement',
            index=models.Index(fields=['from_contact'], name='social_sett_from_co_9c9631_idx'),
        ),
        migrations.AddIndex(
            model_name='settlement',
            index=models.Index(fields=['to_contact'], name='social_sett_to_cont_b45b0e_idx'),
        ),
        migrations.AddConstraint(
            model_name='settlement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('from_contact__isnull', True), ('from_is_owner', True)), models.Q(('from_contact__isnull', False), ('from_is_owner', False)), _connector='OR'), name='settlement_from_valid'),
        ),
        migrations.AddConstraint(
            model_name='settlement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('to_contact__isnull', True), ('to_is_owner', True)), models.Q(('to_contact__isnull', False), ('to_is_owner', False)), _connector='OR'), name='settlement_to_valid'),
        ),
    ]
