# Generated by Django 5.2 on 2026-02-07 21:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('user_id', models.UUIDField(db_index=True, help_text='User to notify.')),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant context.')),
                ('title', models.CharField(help_text='Notification title.', max_length=255)),
                ('message', models.TextField(help_text='Notification message.')),
                ('notification_type', models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=20)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('action_url', models.URLField(blank=True, help_text='Optional action URL.')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'demo_notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', 'is_read', '-created_at'], name='idx_notification_user_read')],
            },
        ),
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('event_type', models.CharField(db_index=True, help_text="Event type (e.g., 'accounts.user.created').", max_length=255)),
                ('event_id', models.UUIDField(db_index=True, help_text='Unique event identifier.')),
                ('correlation_id', models.UUIDField(db_index=True, help_text='Correlation ID for tracing.')),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant context for the event.')),
                ('payload', models.JSONField(help_text='Event payload as JSON.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('retry_count', models.PositiveIntegerField(default=0, help_text='Number of processing attempts.')),
                ('max_retries', models.PositiveIntegerField(default=3, help_text='Maximum retry attempts.')),
                ('last_error', models.TextField(blank=True, help_text='Last processing error message.')),
                ('processed_at', models.DateTimeField(blank=True, help_text='When the event was successfully processed.', null=True)),
                ('scheduled_for', models.DateTimeField(blank=True, db_index=True, help_text='When to attempt processing (for retries).', null=True)),
            ],
            options={
                'verbose_name': 'Outbox Event',
                'verbose_name_plural': 'Outbox Events',
                'db_table': 'demo_outbox_events',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'scheduled_for'], name='idx_outbox_status_scheduled'), models.Index(fields=['event_type', 'status'], name='idx_outbox_type_status')],
            },
        ),
    ]
