# Generated by Django 5.2 on 2026-02-07 21:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('asset_type', models.CharField(choices=[('real_estate', 'Real Estate'), ('vehicle', 'Vehicle'), ('investment', 'Investment'), ('collectible', 'Collectible'), ('receivable', 'Receivable'), ('other', 'Other')], default='other', max_length=20)),
                ('current_value', models.DecimalField(decimal_places=4, max_digits=19)),
                ('currency_code', models.CharField(default='USD', max_length=3)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_included_in_net_worth', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Liability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('liability_type', models.CharField(choices=[('mortgage', 'Mortgage'), ('auto_loan', 'Auto Loan'), ('personal_loan', 'Personal Loan'), ('student_loan', 'Student Loan'), ('credit_card', 'Credit Card'), ('line_of_credit', 'Line of Credit'), ('other', 'Other')], default='other', max_length=20)),
                ('current_balance', models.DecimalField(decimal_places=4, max_digits=19)),
                ('currency_code', models.CharField(default='USD', max_length=3)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('minimum_payment', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('due_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('creditor', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number_masked', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_included_in_net_worth', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Liability',
                'verbose_name_plural': 'Liabilities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('checking', 'Checking'), ('savings', 'Savings'), ('cash', 'Cash'), ('credit_card', 'Credit Card'), ('investment', 'Investment'), ('wallet', 'Wallet'), ('other', 'Other')], default='checking', max_length=20)),
                ('currency_code', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('closed', 'Closed')], default='active', max_length=20)),
                ('institution', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number_masked', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_included_in_net_worth', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'ordering': ['display_order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'name'), name='unique_account_name_per_tenant')],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=7, null=True)),
                ('is_system', models.BooleanField(default=False)),
                ('is_income', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='finance.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_currency', models.CharField(max_length=3)),
                ('to_currency', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=10, max_digits=19)),
                ('effective_date', models.DateField()),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Exchange Rate',
                'verbose_name_plural': 'Exchange Rates',
                'ordering': ['-effective_date'],
                'indexes': [models.Index(fields=['from_currency', 'to_currency', 'effective_date'], name='finance_exc_from_cu_4dcf36_idx')],
                'constraints': [models.UniqueConstraint(fields=('from_currency', 'to_currency', 'effective_date'), name='unique_exchange_rate_per_day')],
            },
        ),
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('key', models.CharField(max_length=255)),
                ('resource_id', models.UUIDField()),
                ('resource_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Idempotency Key',
                'verbose_name_plural': 'Idempotency Keys',
                'indexes': [models.Index(fields=['tenant_id', 'key'], name='finance_ide_tenant__4e5bcd_idx'), models.Index(fields=['expires_at'], name='finance_ide_expires_57ba05_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant_id', 'key'), name='unique_idempotency_key')],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('liability_type', models.CharField(choices=[('mortgage', 'Mortgage'), ('auto_loan', 'Auto Loan'), ('personal_loan', 'Personal Loan'), ('student_loan', 'Student Loan'), ('credit_card', 'Credit Card'), ('line_of_credit', 'Line of Credit'), ('other', 'Other')], default='personal_loan', max_length=20)),
                ('original_principal', models.DecimalField(decimal_places=4, max_digits=19)),
                ('current_balance', models.DecimalField(decimal_places=4, max_digits=19)),
                ('currency_code', models.CharField(default='USD', max_length=3)),
                ('interest_rate', models.DecimalField(decimal_places=4, max_digits=6)),
                ('payment_amount', models.DecimalField(decimal_places=4, max_digits=19)),
                ('payment_frequency', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], default='monthly', max_length=15)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paid_off', 'Paid Off'), ('defaulted', 'Defaulted'), ('deferred', 'Deferred')], default='active', max_length=15)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expected_payoff_date', models.DateField(blank=True, null=True)),
                ('next_payment_date', models.DateField(blank=True, null=True)),
                ('lender', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number_masked', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_included_in_net_worth', models.BooleanField(default=True)),
                ('linked_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_loans', to='finance.account')),
            ],
            options={
                'verbose_name': 'Loan',
                'verbose_name_plural': 'Loans',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit (Money In)'), ('debit', 'Debit (Money Out)')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=19)),
                ('currency_code', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('posted', 'Posted'), ('voided', 'Voided')], default='pending', max_length=10)),
                ('transaction_date', models.DateField()),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.account')),
                ('adjustment_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments', to='finance.transaction')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.category')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=19)),
                ('currency_code', models.CharField(default='USD', max_length=3)),
                ('transfer_date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True, null=True)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transfers', to='finance.account')),
                ('from_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.transaction')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfers', to='finance.account')),
                ('to_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.transaction')),
            ],
            options={
                'verbose_name': 'Transfer',
                'verbose_name_plural': 'Transfers',
                'ordering': ['-transfer_date', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'name'), name='unique_category_name_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['tenant_id', 'account', 'transaction_date'], name='finance_tra_tenant__2f1d4c_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['tenant_id', 'category'], name='finance_tra_tenant__7a6bc2_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['tenant_id', 'status'], name='finance_tra_tenant__ab899b_idx'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('tenant_id', 'idempotency_key'), name='unique_idempotency_key_per_tenant'),
        ),
    ]
