# Generated by Django 5.2 on 2026-02-07 21:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Tenant this user belongs to. For B2C, typically equals user ID.')),
                ('email', models.EmailField(db_index=True, help_text="User's email address (used for login).", max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, help_text="User's first name.", max_length=150)),
                ('last_name', models.CharField(blank=True, help_text="User's last name.", max_length=150)),
                ('role', models.CharField(choices=[('user', 'User'), ('premium', 'Premium'), ('superadmin', 'Super Admin')], db_index=True, default='user', help_text="User's role in the system.", max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('active', 'Active'), ('suspended', 'Suspended'), ('deleted', 'Deleted')], db_index=True, default='pending', help_text='Account status.', max_length=20)),
                ('is_email_verified', models.BooleanField(default=False, help_text='Whether email has been verified.')),
                ('failed_login_attempts', models.PositiveIntegerField(default=0, help_text='Number of consecutive failed login attempts.')),
                ('locked_until', models.DateTimeField(blank=True, help_text='Account locked until this time.', null=True)),
                ('last_login_at', models.DateTimeField(blank=True, help_text='Last successful login timestamp.', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether account has been soft deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='When account was deleted.', null=True)),
                ('is_staff', models.BooleanField(default=False, help_text='Whether user can access admin site.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether user account is active.')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'accounts_users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('email', models.EmailField(help_text='Email to verify.', max_length=254)),
                ('token', models.CharField(db_index=True, max_length=128, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Verification Token',
                'verbose_name_plural': 'Email Verification Tokens',
                'db_table': 'accounts_email_verification_tokens',
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('token', models.CharField(db_index=True, max_length=128, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password Reset Token',
                'verbose_name_plural': 'Password Reset Tokens',
                'db_table': 'accounts_password_reset_tokens',
            },
        ),
        migrations.CreateModel(
            name='RefreshTokenBlacklist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('token_jti', models.CharField(db_index=True, help_text='JWT ID of the blacklisted token.', max_length=255, unique=True)),
                ('blacklisted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='When the original token would have expired.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacklisted_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blacklisted Refresh Token',
                'verbose_name_plural': 'Blacklisted Refresh Tokens',
                'db_table': 'accounts_refresh_token_blacklist',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['tenant_id', 'email'], name='idx_user_tenant_email'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['tenant_id', 'status'], name='idx_user_tenant_status'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'status'], name='idx_user_role_status'),
        ),
    ]
