# Generated by Django 5.2 on 2026-02-07 23:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('code', models.CharField(db_index=True, help_text="Unique code for the tier (e.g., 'free', 'premium').", max_length=50, unique=True)),
                ('name', models.CharField(help_text='Display name for the tier.', max_length=100)),
                ('description', models.TextField(blank=True, default='', help_text='Description of the tier for marketing.')),
                ('limits', models.JSONField(blank=True, default=dict, help_text='Usage limits as JSON. Keys: accounts_max, transactions_monthly, contacts_max, expense_groups_max, api_calls_daily. Empty or 0 means unlimited.')),
                ('features', models.JSONField(blank=True, default=list, help_text='List of feature codes enabled for this tier.')),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0, help_text='Monthly price in USD.', max_digits=10)),
                ('price_yearly', models.DecimalField(decimal_places=2, default=0, help_text='Yearly price in USD.', max_digits=10)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order for displaying tiers.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this tier is available for new subscriptions.')),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default tier for new users.')),
                ('stripe_price_id_monthly', models.CharField(blank=True, default='', help_text='Stripe Price ID for monthly billing.', max_length=255)),
                ('stripe_price_id_yearly', models.CharField(blank=True, default='', help_text='Stripe Price ID for yearly billing.', max_length=255)),
            ],
            options={
                'verbose_name': 'Subscription Tier',
                'verbose_name_plural': 'Subscription Tiers',
                'db_table': 'subscription_tiers',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('expired', 'Expired'), ('incomplete', 'Incomplete')], db_index=True, default='active', help_text='Current subscription status.', max_length=20)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', help_text='Billing cycle (monthly or yearly).', max_length=20)),
                ('current_period_start', models.DateTimeField(blank=True, help_text='Start of the current billing period.', null=True)),
                ('current_period_end', models.DateTimeField(blank=True, help_text='End of the current billing period.', null=True)),
                ('trial_start', models.DateTimeField(blank=True, help_text='When the trial started.', null=True)),
                ('trial_end', models.DateTimeField(blank=True, help_text='When the trial ends.', null=True)),
                ('canceled_at', models.DateTimeField(blank=True, help_text='When the subscription was canceled.', null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False, help_text='Whether to cancel at the end of the current period.')),
                ('payment_provider', models.CharField(default='stripe', help_text='Payment provider name.', max_length=50)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='External subscription ID (e.g., Stripe subscription ID).', max_length=255, null=True)),
                ('external_customer_id', models.CharField(blank=True, db_index=True, help_text='External customer ID (e.g., Stripe customer ID).', max_length=255, null=True)),
                ('user', models.OneToOneField(help_text='The user this subscription belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
                ('tier', models.ForeignKey(help_text='The subscription tier.', on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.subscriptiontier')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'db_table': 'subscriptions',
            },
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('usage_type', models.CharField(db_index=True, help_text='Type of usage being tracked.', max_length=50)),
                ('count', models.PositiveIntegerField(default=0, help_text='Usage count for the period.')),
                ('period_start', models.DateField(help_text='Start of the tracking period.')),
                ('period_end', models.DateField(blank=True, help_text='End of the tracking period.', null=True)),
                ('user', models.ForeignKey(help_text='The user this usage record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usage Record',
                'verbose_name_plural': 'Usage Records',
                'db_table': 'usage_records',
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['user', 'usage_type', 'period_start'], name='usage_recor_user_id_37fef1_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'usage_type', 'period_start'), name='unique_usage_per_user_type_period')],
            },
        ),
    ]
