# Generated by Django 5.2 on 2026-02-07 23:04

from django.db import migrations


def create_default_tiers(apps, schema_editor):
    """Create default subscription tiers."""
    SubscriptionTier = apps.get_model("subscriptions", "SubscriptionTier")

    # Free tier
    SubscriptionTier.objects.create(
        code="free",
        name="Free",
        description="Basic personal finance tracking with essential features.",
        limits={
            "accounts_max": 3,
            "transactions_monthly": 500,
            "contacts_max": 10,
            "expense_groups_max": 2,
            "api_calls_daily": 0,  # No API access
        },
        features=[
            "export.csv",
            "social.basic",
        ],
        price_monthly=0,
        price_yearly=0,
        display_order=0,
        is_active=True,
        is_default=True,
    )

    # Premium tier
    SubscriptionTier.objects.create(
        code="premium",
        name="Premium",
        description="Unlimited access with advanced features and API access.",
        limits={},  # Empty = unlimited
        features=[
            "reports.advanced",
            "reports.export_pdf",
            "export.csv",
            "export.json",
            "export.pdf",
            "api.access",
            "social.basic",
            "social.full",
            "finance.view_sensitive",
            "finance.view_rates",
            "finance.view_notes",
            "finance.bulk_import",
            "finance.analytics",
            "expense_groups.unlimited_members",
        ],
        price_monthly=9.99,
        price_yearly=99.99,
        display_order=1,
        is_active=True,
        is_default=False,
    )

    # Enterprise tier (placeholder for future)
    SubscriptionTier.objects.create(
        code="enterprise",
        name="Enterprise",
        description="Custom solutions for businesses with dedicated support.",
        limits={},  # Unlimited
        features=[
            "reports.advanced",
            "reports.export_pdf",
            "export.csv",
            "export.json",
            "export.pdf",
            "api.access",
            "social.basic",
            "social.full",
            "finance.view_sensitive",
            "finance.view_rates",
            "finance.view_notes",
            "finance.bulk_import",
            "finance.analytics",
            "expense_groups.unlimited_members",
        ],
        price_monthly=49.99,
        price_yearly=499.99,
        display_order=2,
        is_active=False,  # Not available yet
        is_default=False,
    )


def create_user_subscriptions(apps, schema_editor):
    """Create subscriptions for existing users based on their role."""
    User = apps.get_model("accounts", "User")
    Subscription = apps.get_model("subscriptions", "Subscription")
    SubscriptionTier = apps.get_model("subscriptions", "SubscriptionTier")

    free_tier = SubscriptionTier.objects.get(code="free")
    premium_tier = SubscriptionTier.objects.get(code="premium")

    for user in User.objects.all():
        # Determine tier based on role
        if user.role in ("premium", "superadmin"):
            tier = premium_tier
        else:
            tier = free_tier

        # Create subscription
        Subscription.objects.create(
            user=user,
            tier=tier,
            status="active",
            billing_cycle="monthly",
        )


def reverse_tiers(apps, schema_editor):
    """Remove all tiers."""
    SubscriptionTier = apps.get_model("subscriptions", "SubscriptionTier")
    SubscriptionTier.objects.all().delete()


def reverse_subscriptions(apps, schema_editor):
    """Remove all subscriptions."""
    Subscription = apps.get_model("subscriptions", "Subscription")
    Subscription.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
        ("accounts", "0001_initial"),  # Ensure accounts app is migrated first
    ]

    operations = [
        migrations.RunPython(create_default_tiers, reverse_tiers),
        migrations.RunPython(create_user_subscriptions, reverse_subscriptions),
    ]
